stage_1:
  target: stage1.RAE
  ckpt: null
  params:
    encoder_name: dinov3mls-vit-l16[layers=1.2.3.4.5.6.7.8.9.10.11.12.13.14.15.16.17.18.19.20.21.22.23]
    resolution: 512
    decoder_config_path: configs/decoder/ViTXL
    pretrained_decoder_path: pretrained_models/stage1/imagenet/dinov3l-k23/decoder.pt
    noise_tau: 0.0

training:
  global_batch_size: 8
  num_workers: 2
  image_size: 512

dataset:
  target: imagenet
  type: imagefolder
  data_dir: /scratch/zs3325/datasets/imagenet
  split: val
  condition_type: label
  resize_size: 768

eval:
  eval_dir: results/stage1/eval
  datasets:
    imagenet:
      target: imagenet
      type: imagefolder
      data_dir: /scratch/zs3325/datasets/imagenet
      split: val
      condition_type: label
      resize_size: 768
      num_samples: 2048
      metrics: [psnr, ssim, lpips]
